---
title: "Introduction to Github"
output:
  ioslides_presentation:
    widescreen: false
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Before the workshop

- Create Github account
- Star + Watch this course_github repository and clinicalbrainlab.github.io repository
- Read Dom's blogpost about why psychologist should use Github


## Pre-requisite 

- Have you created your Github account?

## what is Github?

- Open-source environment 
- Abit about history

- Motivation:
  - develop software or some useful functions for yourself, would like to share (e.g. email automation)
  - experimenta paradigms (e.g cocon, compex span)
  - follow updates of functions (in R or Python, or Matlab ^^) that are developed and maintained on Github, raise issues (e.g tidyverse, easystas, numpy, pandas...)
  - Freely available data (e.g. JHU covid-19)
  
## Exercise 1: Create a repository

- Demo
- Initialize with readme.md
- Show some markdown stuffs (title, subtitle, bullet, bold, italic, link)
- Show commit history

## Exercise 2: Fork repository

- Fork the website repository (explain a little bit about fork)
- update profile (show step-by-step)

## Using Github

  - share your work (create a repo)
  - follow updates of functions (watch NeuroKit)
  - raise issue (show isuee)
  - download available data (e.g. JHU covid-19)

<!-- note to self --> how to troubleshoot during the session?

## Next session

- more advanced tools
- more details about Github
